weathersite/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/accounts/password_reset_complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("verify-code/", views.verify_code, name="verify_code"),
    path("reset-password/", views.reset_password, name="reset_password"),
]

weathersite/weather/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("autocomplete/", views.autocomplete, name="autocomplete"),
    path("tomorrow/", views.tomorrow, name="tomorrow"),
    path("weekly/", views.weekly, name="weekly"),
]

weathersite/weathersite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("", include("weather.urls")),
]

weathersite/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import random


class PasswordResetCode(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)

    def generate_code(self):
        self.code = str(random.randint(100000, 999999))
        self.save()

weathersite/weather/models.py
from django.db import models
from django.conf import settings


class SavedCity(models.Model):
    city_name = models.CharField(max_length=100)
    state = models.CharField(max_length=100, blank=True, null=True)
    country_code = models.CharField(max_length=10)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="saved_cities"
    )

    def __str__(self):
        return f"{self.city_name}, {self.country_code}"

weathersite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

weathersite/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm
from django.contrib import messages
from django.contrib.auth.models import User


def signup_view(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        username = request.POST.get("username")

        if User.objects.filter(email=email).exists():
            messages.error(
                request, "This email is already in use. Please choose another."
            )
            return redirect("accounts:signup")

        User.objects.create_user(username=username, email=email, password=password)

        return redirect("home")

    return render(request, "accounts/signup.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home")
        # Show error
        messages.error(request, "Invalid username or password")
        # Instead of redirect, render template so the message displays immediately
        return render(request, "accounts/login.html")
    return render(request, "accounts/login.html")


def logout_view(request):
    logout(request)
    return render(request, "accounts/logout.html")


from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.contrib import messages
from .models import PasswordResetCode
from django.utils import timezone
from datetime import timedelta


def forgot_password(request):
    if request.method == "POST":
        email = request.POST.get("email")
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            messages.error(request, "No account with this email.")
            return redirect("forgot_password")

        reset_code = PasswordResetCode.objects.create(user=user)
        reset_code.generate_code()

        send_mail(
            "Password Reset Code",
            f"Your password reset code is: {reset_code.code}",
            None,
            [email],
        )

        request.session["reset_user_id"] = user.id
        return redirect("verify_code")

    return render(request, "accounts/forgot_password.html")


def verify_code(request):
    if request.method == "POST":
        input_code = request.POST.get("code")
        user_id = request.session.get("reset_user_id")
        user = User.objects.get(id=user_id)
        code_obj = PasswordResetCode.objects.filter(user=user).last()

        if code_obj.code == input_code:
            return redirect("reset_password")
        else:
            messages.error(request, "Incorrect code.")
            return redirect("verify_code")

    return render(request, "accounts/verify_code.html")


def reset_password(request):
    if request.method == "POST":
        password = request.POST.get("password")
        repeat = request.POST.get("password2")

        if password != repeat:
            messages.error(request, "Passwords do not match.")
            return redirect("reset_password")

        user_id = request.session.get("reset_user_id")
        user = User.objects.get(id=user_id)
        user.set_password(password)
        user.save()

        messages.success(request, "Password changed successfully.")
        return redirect("login")

    return render(request, "accounts/reset_password.html")

weathersite/weather/views.py
from django.views.generic import TemplateView
from .utils import home, tomorrow, weekly, autocomplete


class MyView(TemplateView):
    template_name = "my_template.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["home"] = home()
        context["tomorrow"] = tomorrow()
        context["weekly"] = weekly()
        context["autocomplete"] = autocomplete()
        return context


# ip_address = request.META.get("HTTP_X_FORWARDED_FOR")
# if ip_address:
#     ip_address = ip_address.split(",")[0]
# else:
#     ip_address = request.META.get("REMOTE_ADDR")
# ip_address = "8.8.8.8"  # For testing purposes
# url = f"https://ipapi.co/{ip_address}/json/"
# response = requests.get(url, timeout=5)
# data = response.json()
# context = {
#     "city": data.get("city"),
#     "country": data.get("country_name"),
#     "region": data.get("region"),
# }
# print(data)

weathersite/accounts/templates/accounts/forgot_password.html
{% block content %}
<style>
  body {
    margin: 0;
    font-family: Arial, sans-serif;
    background-color: #252323;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
  }

  .login-back {
    background-color: #fff;
    padding: 40px;
    border-radius: 10px;
    width: 350px;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    text-align: center;
  }

  .login-back h2 {
    margin-bottom: 30px;
  }

  .login-back input[type="email"] {
    width: 100%;
    padding: 12px;
    margin: 8px 0 20px 0;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
  }

  .login-back button {
    width: 100%;
    background-color: #0066ff;
    color: white;
    padding: 12px;
    border: none;
    border-radius: 5px;
    font-size: 16px;
    cursor: pointer;
  }

  .login-back button:hover {
    background-color: #0052cc;
  }

</style>

<div class="login-back">
  <h2>Forgot Password</h2>
  <p>Please enter your Email to reset the password</p>
  <form method="post">
    {% csrf_token %}
    <input type="email" name="email" placeholder="Email" id="email" required>
    <button type="submit">Send Code</button>
  </form>
</div>

{% endblock %}

weathersite/accounts/templates/accounts/login.html
{% block content %}
<style>
    body {
        margin: 0;
        font-family: Arial, sans-serif;
        background-color: #252323;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .login-back {
        background-color: #fff;
        padding: 40px;
        border-radius: 10px;
        width: 350px;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
        text-align: center;
    }

    .login-back h2 {
        margin-bottom: 30px;
    }

    .login-back input[type="text"],
    .login-back input[type="password"] {
        width: 100%;
        padding: 12px;
        margin: 8px 0 20px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    .login-back button {
        width: 100%;
        background-color: #0066ff;
        color: white;
        padding: 12px;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
    }

    .signin-back button:hover {
        background-color: #0052cc;
    }

    .signup {
        margin-top: 20px;
        font-size: 14px;
    }

    .signup a {
        color: #0066ff;
        text-decoration: none;
    }

    .signup a:hover {
        text-decoration: underline;
    }

    .forgot {
        display: block;
        margin-bottom: 20px;
        font-size: 14px;
        color: #555;
        text-decoration: none;
    }

    .forgot:hover {
        text-decoration: underline;
    }

    .alert {
        padding: 10px;
        margin-bottom: 15px;
        border-radius: 5px;
    }

    .alert.error {
        color: #ff4d4f;
        font-size: 14px;
        text-align: center;
        margin-top: 10px;
    }
</style>

<div class="login-back">
    <h2>Sign In</h2>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Name or Email" id="id_username" required>
        <input type="password" name="password" placeholder="Password" id="id_password" required>
        <a href="{% url 'accounts:forgot_password' %}" class="forgot">Forgot Password?</a>
        <button id="login-btn" type="submit">Sign In</button>
    </form>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="signup">
        Don't have an account? <a href="{% url 'accounts:signup' %}">Sign Up</a>
    </div>
</div>
<script>
    setTimeout(() => {
        const msg = document.querySelector('.alert.error');
        if (msg) msg.style.display = 'none';
    }, 3000);
</script>

{% endblock %}

weathersite/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been logged out.</p>
  <p><a href="{% url 'accounts:login' %}">Log in again</a></p>
{% endblock %}

weathersite/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block navbar %}{% endblock %}

{% block content %}
<style>
  body {
    margin: 0;
    font-family: Arial, sans-serif;
    background-color: #252323;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
  }

  .signup-back {
    background-color: #fff;
    padding: 40px;
    border-radius: 10px;
    width: 350px;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    text-align: center;
  }

  .signup-back h2 {
    margin-bottom: 30px;
  }

  .flash-message {
    color: #ff4d4f;
    font-size: 14px;
    text-align: center;
    margin-top: 10px;
  }

  .signup-back input[type="text"],
  .signup-back input[type="email"],
  .signup-back input[type="password"] {
    width: 100%;
    padding: 12px;
    margin: 8px 0 20px 0;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
  }

  .signup-back button {
    width: 100%;
    background-color: #0066ff;
    color: white;
    padding: 12px;
    border: none;
    border-radius: 5px;
    font-size: 16px;
    cursor: pointer;
  }

  .signup-back button:hover {
    background-color: #0052cc;
  }

  .signin {
    margin-top: 20px;
    font-size: 14px;
  }

  .signin a {
    color: #0066ff;
    text-decoration: none;
  }

  .signin a:hover {
    text-decoration: underline;
  }
</style>

<div class="signup-back">
  <h2>Sign Up</h2>

  <form method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Name" id="id_username" required>
    <input type="email" name="email" placeholder="Email" id="id_email" required>
    <input type="password" name="password" placeholder="Password" id="id_password" required>
    <button id="signup-btn" type="submit">Sign Up</button>
  </form>

  {% if messages %}
  {% for message in messages %}
  <p class="flash-message">{{ message }}</p>
  {% endfor %}
  {% endif %}


  <div class="signin">
    Already have an account? <a href="{% url 'accounts:login' %}">Sign In</a>
  </div>
</div>


<script>
  setTimeout(() => {
    const msg = document.querySelector('.flash-message');
    if (msg) msg.style.display = 'none';
  }, 3000);
</script>

{% endblock %}

weathersite/accounts/templates/accounts/verify_code.html
<form method="post">
    {% csrf_token %}
    <h2>Enter Code</h2>
    <input type="text" name="code" placeholder="6-digit code" required>
    <button type="submit">Verify</button>
</form>

weathersite/templates/base.html
<html>

<head>
  <meta charset="utf-8">
  <title>Weathersite</title>
</head>

<body>

  {% block navbar %}
  <nav>
    <!-- <a href="{% url 'home' %}">Home</a> |
    <a href="{% url 'accounts:signup' %}">Sign up</a> |
    <a href="{% url 'accounts:login' %}">Sign in</a> -->
  </nav>
  <hr>
  {% endblock %}

  {% block content %}{% endblock %}
</body>

</html>

weathersite/templates/weather/home.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<link rel="stylesheet" href="{% static 'css_files/home.css' %}">

</head>

<body>

    <header>
        <div style="font-size: 45px; font-weight: 300;">
            Sunlit<br>
            <span id="current-time" style="font-size: 16px; opacity: 0.7;"></span>
        </div>

        <div class="nav-menu">
            <div id="today-tab" class="active"><a href="{% url 'home' %}">Today</a></div>
            <div id="tomorrow-tab"> <a href="{% url 'tomorrow' %}">Tomorrow</a></div>
            <div id="weekly-tab"> <a href="{% url 'weekly' %}">Weekly Forecast</a></div>

        </div>

        <a href="{% url 'accounts:login' %}"
            style="font-size: 20px; color: #fff; text-decoration: none; align-self: center;">
            Sign In
        </a>

    </header>
    <div class="search-container" style="position: relative;">
        <div class="search-bar">
            <form method="get" style="display: flex; align-items: center; width: 100%;">
                <img src="{% static 'weather_icons/search-logo.png' %}" alt="search">
                <input id="searchInput" type="text" name="city" placeholder="Search location..." style="
                border: none;
                background: transparent;
                outline: none;
                width: 100%;
                font-size: 16px;
                color: #555;
            ">
            </form>
        </div>

        <!-- Error message container -->
        {% if error %}
        <div id="search-error" style="
    color: #fff;
    background-color: #e74c3c;
    padding: 6px 10px;
    margin-top: 3px;
    border-radius: 4px;
    font-size: 14px;
    opacity: 1;
    transition: opacity 0.5s;
    position: absolute; /* position relative to search bar */
    z-index: 10;
">
            {{ error }}
        </div>
        {% else %}
        <div id="search-error" style="display:none;"></div>
        {% endif %}

        <div id="suggestions" class="suggestions-box"></div>
    </div>

    </div>


    <div class="carousel-container">


        <div class="weather-card">
            <div class="weather-header">{{ city }}📍<br>

                <span id="weather-date" style="font-size: 14px; opacity: 0.7;"></span>
            </div>

            <div class="weather-center">
                {%if description == "broken clouds" or description == "overcast clouds"%}
                <img src="{% static 'weather_icons/cloud-logo.png' %}" alt="weather">
                {%elif description == "clear sky"%}
                <img src="{% static 'weather_icons/sunny-logo.png' %}" alt="weather">
                {%elif description == " few clouds"%}
                <img src="{% static 'weather_icons/few-cloud.png' %}" alt="weather">
                {%elif description == "scattered clouds"%}
                <img src="{% static 'weather_icons/cloud.png' %}" alt="weather">
                {%elif description == "shower rain"%}
                <img src="{% static 'weather_icons/storm-rain-logo.png' %}" alt="weather">
                {%elif description == "rain"%}
                <img src="{% static 'weather_icons/rain-logo.png' %}" alt="weather">
                {%elif description == "thunderstorm"%}
                <img src="{% static 'weather_icons/storm-logo.png' %}" alt="weather">
                {%elif description == "snow"%}
                <img src="{% static 'weather_icons/snow-logo.png' %}" alt="weather">
                {%elif description == "mist"%}
                <img src="{% static 'weather_icons/mist.png' %}" alt="weather">
                {%endif%}
                <div class="weather-temp">{{ temperature|floatformat:0 }}°C</div>

            </div>

            <div class="weather-stats">
                <div class="stat-block"><span>HUMIDITY</span><br>{{humidity}}</div>
                <div class="stat-block"><span>VISIBILITY</span><br>{{visibility}}</div>
                <div class="stat-block"><span>AIR PRESSURE</span><br>{{ air_pressure }}</div>
                <div class="stat-block"><span>WIND</span><br>{{speed}}</div>
            </div>
        </div>

    </div>

    <div class="hourly-container">
        {% for h in hourly %}
        <div class="hour-box">
            <div class="hour-time">
                {{ h.dt_txt|slice:"11:16" }}
            </div>

            {%if h.weather.0.description == "broken clouds" or h.weather.0.description == "overcast clouds"%}
            <img src="{% static 'weather_icons/cloud-logo.png' %}" alt="weather">
            {%elif h.weather.0.description == "clear sky"%}
            <img src="{% static 'weather_icons/sunny-logo.png' %}" alt="weather">
            {%elif h.weather.0.description == " few clouds"%}
            <img src="{% static 'weather_icons/few-cloud.png' %}" alt="weather">
            {%elif h.weather.0.description == "scattered clouds"%}
            <img src="{% static 'weather_icons/cloud.png' %}" alt="weather">
            {%elif h.weather.0.description == "shower rain"%}
            <img src="{% static 'weather_icons/storm-rain-logo.png' %}" alt="weather">
            {%elif h.weather.0.description == "rain"%}
            <img src="{% static 'weather_icons/rain-logo.png' %}" alt="weather">
            {%elif h.weather.0.description == "thunderstorm"%}
            <img src="{% static 'weather_icons/storm-logo.png' %}" alt="weather">
            {%elif h.weather.0.description == "snow"%}
            <img src="{% static 'weather_icons/snow-logo.png' %}" alt="weather">
            {%elif h.weather.0.description == "mist"%}
            <img src="{% static 'weather_icons/mist.png' %}" alt="weather">
            {%else%}
            <img src="{% static 'weather_icons/few-cloud.png' %}" alt="icon">
            {%endif%}

            <div class="hour-temp">
                {{ h.main.temp|floatformat:0 }}°C
            </div>
        </div>
        {% endfor %}
    </div>

    <footer>
        <div style="margin-bottom: 20px; font-size: 22px;">Sunlit</div>
        <div style="margin-top: 20px;">
            <a id="instagram" href="https://www.instagram.com/_._.sunlit_._/" style="margin-left: 15px;">
                <img src="{% static 'social_media/instagram-logo.png' %}" alt="Instagram">
            </a>
            <a id="facebook" href="https://www.facebook.com/profile.php?id=61585156410781">
                <img src="{% static 'social_media/facebook-logo.png' %}" alt="Facebook">
            </a>
        </div>
    </footer>

    <script>
        function updateTime() {
            const timeElement = document.getElementById('current-time');
            const now = new Date();
            let hours = now.getHours();
            let minutes = now.getMinutes();
            minutes = minutes < 10 ? '0' + minutes : minutes;
            const ampm = hours >= 12 ? 'pm' : 'am';
            hours = hours % 12;
            hours = hours ? hours : 12;
            timeElement.textContent = hours + ':' + minutes + ' ' + ampm;
        }

        function updateDate(offset = 0) {
            const dateElement = document.getElementById('weather-date');
            const now = new Date();
            now.setDate(now.getDate() + offset); // offset 0 = today, 1 = tomorrow

            const options = { month: 'short', day: 'numeric', weekday: 'short' };
            dateElement.textContent = now.toLocaleDateString('en-US', options);
        }

        updateTime();
        setInterval(updateTime, 60000);


        updateDate(0);

        //Today/Tomorrow
        const todayTab = document.getElementById('today-tab');
        const tomorrowTab = document.getElementById('tomorrow-tab');
        const weeklyTab = document.getElementById('weekly-tab');



        document.getElementById("searchInput").addEventListener("input", function () {
            const query = this.value.trim();
            const suggestions = document.getElementById("suggestions");

            if (query.length < 2) {
                suggestions.innerHTML = "";
                return;
            }

            fetch(`/autocomplete?query=${encodeURIComponent(query)}`)
                .then(res => res.json())
                .then(list => {
                    suggestions.innerHTML = "";

                    list.forEach(city => {
                        const item = document.createElement("div");
                        item.classList.add("suggestion-item");

                        item.textContent = `${city.city}${city.region ? ", " + city.region : ""}, ${city.country_code}`;

                        item.onclick = () => {
                            document.getElementById("searchInput").value = city.city;
                            suggestions.innerHTML = "";
                            window.location.href = `/?city=${city.city}`;
                        };

                        suggestions.appendChild(item);
                    });
                });
        });

        // Automatically hide search error after 3 seconds
        const errorDiv = document.getElementById("search-error");
        if (errorDiv && errorDiv.textContent.trim() !== "") {
            setTimeout(() => {
                errorDiv.style.opacity = 0;
                setTimeout(() => {
                    errorDiv.style.display = "none";
                }, 500); // match the CSS transition
            }, 3000); // 3 seconds
        }


    </script>

</body>

</html>
{% endblock %}

weathersite/templates/weather/weekly.html
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css_files/weekly.css' %}" />

<div class="page">

  <!-- Header -->
  <header class="header">
    <div class="logo">
      <h1>Sunlit</h1>
      <span id="current-time"></span>
    </div>

    <nav class="nav">
      <a id="today-tab" href="/">Today</a>
      <a id="tomorrow-tab" href="/tomorrow">Tomorrow</a>
      <a id="weekly-tab" class="active" href="/weekly">Weekly Forecast</a>
    </nav>
  </header>

  <div class="search-container" style="position: relative; width: 400px; margin: 0 auto;">
    <div class="search-bar" style="
        display: flex;
        align-items: center;
        background: #f0f0f0;
        padding: 8px 12px;
        border-radius: 25px;
        border: 1px solid #ccc;
    ">
      <form method="get" style="display: flex; align-items: center; width: 100%;">
        <img src="{% static 'weather_icons/search-logo.png' %}" alt="search" style="
            width: 20px;
            height: 20px;
            margin-right: 10px;
        ">
        <input id="searchInput" type="text" name="city" placeholder="Search location..." style="
            border: none;
            background: transparent;
            outline: none;
            width: 100%;
            font-size: 16px;
            color: #333;
        ">
      </form>
    </div>
  </div>


  <!-- Error message container -->
  {% if error %}
  <div id="search-error" style="
    color: #fff;
    background-color: #e74c3c;
    padding: 6px 10px;
    margin-top: 3px;
    border-radius: 4px;
    font-size: 14px;
    opacity: 1;
    transition: opacity 0.5s;
    position: absolute; /* position relative to search bar */
    z-index: 10;
">
    {{ error }}
  </div>
  {% else %}
  <div id="search-error" style="display:none;"></div>
  {% endif %}

  <div id="suggestions" class="suggestions-box"></div>
</div>

</div>


<!-- Weekly date range -->
<div id="weather-date" class="week-range"></div>

<section class="forecast">
  {% for day in weekly %}
  <div class="weather-center">
    {% if day.weather_desc == "broken clouds" or day.weather_desc == "overcast clouds" %}
    <img src="{% static 'weather_icons/cloud-logo.png' %}" alt="weather">
    {% elif day.weather_desc == "clear sky" %}
    <img src="{% static 'weather_icons/sunny-logo.png' %}" alt="weather">
    {% elif day.weather_desc == "few clouds" %}
    <img src="{% static 'weather_icons/few-cloud.png' %}" alt="weather">
    {% elif day.weather_desc == "scattered clouds" %}
    <img src="{% static 'weather_icons/cloud.png' %}" alt="weather">
    {% elif day.weather_desc == "shower rain" %}
    <img src="{% static 'weather_icons/storm-rain-logo.png' %}" alt="weather">
    {% elif day.weather_desc == "rain" %}
    <img src="{% static 'weather_icons/rain-logo.png' %}" alt="weather">
    {% elif day.weather_desc == "thunderstorm" %}
    <img src="{% static 'weather_icons/storm-logo.png' %}" alt="weather">
    {% elif day.weather_desc == "snow" %}
    <img src="{% static 'weather_icons/snow-logo.png' %}" alt="weather">
    {% elif day.weather_desc == "mist" %}
    <img src="{% static 'weather_icons/mist.png' %}" alt="weather">
    {% else %}
    <img src="{{ day.icon }}" alt="weather">
    {% endif %}
    <div>{{ day.temp_min }}° / {{ day.temp_max }}°</div>
    <div>Humidity: {{ day.humidity }}%</div>
    <div>Wind: {{ day.wind }} m/s</div>
  </div>
  {% endfor %}
</section>



<footer>
  <div style="margin-bottom: 20px; font-size: 22px;">Sunlit</div>
  <div style="margin-top: 20px;">
    <a href="https://www.instagram.com/_._.sunlit_._/" style="margin-left: 15px;">
      <img src="{% static 'social_media/instagram-logo.png' %}" alt="Instagram">
    </a>
    <a href="https://www.facebook.com/profile.php?id=61585156410781">
      <img src="{% static 'social_media/facebook-logo.png' %}" alt="Facebook">
    </a>
  </div>
</footer>


<script>
  // ----------------------
  // Update Current Time
  // ----------------------
  function updateTime() {
    const timeElement = document.getElementById("current-time");
    const now = new Date();

    let hours = now.getHours();
    let minutes = now.getMinutes();
    minutes = minutes < 10 ? "0" + minutes : minutes;

    const ampm = hours >= 12 ? "pm" : "am";
    hours = hours % 12 || 12;

    timeElement.textContent = `${hours}:${minutes} ${ampm}`;
  }

  updateTime();
  setInterval(updateTime, 60000);

  // ----------------------
  // Load Weekly Forecast
  // ----------------------
  function loadWeeklyWeather() {
    const params = new URLSearchParams(window.location.search);
    const city = params.get("city") || "Yerevan";

    fetch(`/weekly/?city=${city}&format=json`)
      .then((res) => res.json())
      .then((data) => {
        const container = document.querySelector(".forecast");
        container.innerHTML = "";

        data.weekly.forEach((day) => {
          const card = document.createElement("div");
          card.classList.add("day-card");

          card.innerHTML = `
          <h3>${day.date}</h3>
          <img class="icon" src="${day.icon}" alt="Weather icon">
          <div class="temp">${day.temp_min}° / ${day.temp_max}°</div>
        `;

          container.appendChild(card);
        });
      })
      .catch((err) => console.error("Error loading weekly forecast:", err));
  }

  document.addEventListener("DOMContentLoaded", loadWeeklyWeather);

  // ----------------------
  // Autocomplete Search
  // ----------------------
  const input = document.getElementById("searchInput");
  const suggestions = document.getElementById("suggestions");

  input.addEventListener("input", function () {
    const query = this.value.trim();

    if (query.length < 2) {
      suggestions.innerHTML = "";
      return;
    }

    fetch(`/autocomplete?query=${encodeURIComponent(query)}`)
      .then((res) => res.json())
      .then((list) => {
        suggestions.innerHTML = "";

        list.forEach((city) => {
          const item = document.createElement("div");
          item.classList.add("suggestion-item");

          item.textContent = `${city.city}${city.region ? ", " + city.region : ""
            }, ${city.country_code}`;

          item.onclick = () => {
            input.value = city.city;
            suggestions.innerHTML = "";
            window.location.href = `/weekly?city=${city.city}`;
          };

          suggestions.appendChild(item);
        });
      });
  });

  // Automatically hide search error after 3 seconds
  const errorDiv = document.getElementById("search-error");
  if (errorDiv && errorDiv.textContent.trim() !== "") {
    setTimeout(() => {
      errorDiv.style.opacity = 0;
      setTimeout(() => {
        errorDiv.style.display = "none";
      }, 500); // match the CSS transition
    }, 3000); // 3 seconds
  }

</script>
{% endblock %}